swagger: '2.0'
info:
  description: This is an API for gyms to keep track of member activities
  version: 1.0.0
  title: Gym Membership API
  # put the contact info for your development or API team
  contact:
    email: you@your-company.com

  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

# tags are used for organizing operations
tags:
- name: admins
  description: Secured Admin-only calls
- name: developers
  description: Operations available to regular developers

paths:
  /scan_in:
    post:
      tags:
      - admins
      summary: Records member scan information
      operationId: app.scan_in
      description: Stores a member scan inforamtion
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: ScanRecord
        description: Scan information to add
        schema:
          $ref: '#/definitions/ScanRecord'
      responses:
        201:
          description: record created
        400:
          description: invalid input, object invalid

  /body_info:
    post:
      tags:
      - admins
      summary: Updates member information
      operationId: app.update_body_info
      description: Updates member weight and body fat
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: BodyInfoUpdate
        description: Body information to update
        schema:
          $ref: '#/definitions/BodyInfoUpdate'
      responses:
        201:
          description: informaion updated
        400:
          description: invalid input, object invalid

definitions:
  ScanRecord:
    type: object
    required:
    - member_id
    - store_id
    - timestamp
    properties:
      member_id:
        type: string
        format: uuid
        example: d290f1ee-6c54-4b01-90e6-d701748f0851
      store_id:
        type: string
        example: A12345
      timestamp:
        type: string
        format: date-time
        example: 2016-08-29T09:12:33.001Z
  BodyInfoUpdate:
    type: object
    required:
    - member_id
    - store_id
    - body_info
    - timestamp
    properties:
      member_id:
        type: string
        format: uuid
        example: d290f1ee-6c54-4b01-90e6-d701748f0851
      store_id:
        type: string
        example: A12345
      body_info:
        $ref: '#/definitions/BodyInfo'
      timestamp:
        type: string
        format: date-time
        example: 2016-08-29T09:12:33.001Z

  BodyInfo:
    type: object
    required:
    - member_id
    - weight
    - body_fat
    properties:
      member_id:
        type: string
        format: uuid
        example: d290f1ee-6c54-4b01-90e6-d701748f0851
      weight:
        type: integer
        example: 80
      body_fat:
        type: integer
        example: 10